site_name: My Docs

theme:
  name: material

plugins:
    - search
    - autorefs
    - mknotebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()
                    - import jaxtyping
                    - jaxtyping.set_array_name_format("array")

                selection:
                    inherited_members: true
                rendering:
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false 
                    members_order: source 
                    heading_level: 4

site_name: Stamox
site_description: The documentation for the Stamox software library.
site_author: Yaobo Jia

repo_url: https://github.com/jiayaobo/stamox
repo_name: jiayaobo/stamox

