site_name: My Docs

theme:
  name: material

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()
                    - import jaxtyping
                    - jaxtyping.set_array_name_format("array")

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                rendering:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4

site_name: Stamox
site_description: The documentation for the Stamox software library.
site_author: Yaobo Jia

repo_url: https://github.com/jiayaobo/stamox
repo_name: jiayaobo/stamox

